version: "3.8"

networks:
  app-tier:
    driver: bridge

volumes:
  dbdemo:

services:
  dbdemo:
    image: bitnami/postgresql:14.4.0
    environment:
      - POSTGRESQL_PASSWORD=gHteuivwdvkew4wt
      - POSTGRESQL_DATABASE=stunning-couscous
    ports:
      - 5432:5432
    networks:
      - app-tier
    volumes:
      - dbdemo:/bitnami/postgresql
  appdemo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRESQL_PASSWORD=gHteuivwdvkew4wt
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=stunning-couscous
      - POSTGRESQL_HOST=dbdemo
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-tier
    volumes:
      - .:/opt/app
