version: "3.8"

networks:
  app-tier:
    driver: bridge

volumes:
  db:

services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    volumes:
      - db:/bitnami/mysql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - app-tier
    volumes:
      - .:/opt/app
